### ISSUE TITLE
Wrong state class, expecting View State but received class android.widget.ScrollView$SavedState instead

### ISSUE THREAD

**Issue by jcnoir** [abarisain/dmix#391]
I had this crash just once. It does not speak much to me (seems linked to noResultLayout) :

20990-20990/com.namelessdev.mpdroid E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.namelessdev.mpdroid, PID: 20990
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.namelessdev.mpdroid/com.namelessdev.mpdroid.MainMenuActivity}: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.widget.ScrollView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/noResultLayout. Make sure other views do not use the same id.
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3738)
            at android.app.ActivityThread.access$900(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.widget.ScrollView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/noResultLayout. Make sure other views do not use the same id.
            at android.view.View.onRestoreInstanceState(View.java:12823)
            at android.view.View.dispatchRestoreInstanceState(View.java:12799)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2637)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2643)
            at android.view.View.restoreHierarchyState(View.java:12777)
            at android.support.v4.app.Fragment.restoreViewState(Fragment.java:447)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:949)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
            at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1884)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:566)
            at com.namelessdev.mpdroid.MainMenuActivity.onStart(MainMenuActivity.java:237)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
            at android.app.Activity.performStart(Activity.java:5241)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2168)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3738)
            at android.app.ActivityThread.access$900(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by ShawnRacine** [comment]
In my case, I added a code "indicator.setId(android.R.id.switch_widget);" in my custom view, and deleted that code work out this error.
