### ISSUE TITLE
InflateException SmoothProgressBar

### ISSUE THREAD

**Issue by hurzl** [abarisain/dmix#494]
```
E/AndroidRuntime( 7359): FATAL EXCEPTION: main
E/AndroidRuntime( 7359): Process: com.namelessdev.mpdroid, PID: 7359
E/AndroidRuntime( 7359): android.view.InflateException: Binary XML file line #37: Error inflating class fr.castorflex.android.smoothprogressbar.SmoothProgressBar
E/AndroidRuntime( 7359):        at android.view.LayoutInflater.createView(LayoutInflater.java:620)
E/AndroidRuntime( 7359):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
E/AndroidRuntime( 7359):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
E/AndroidRuntime( 7359):        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/AndroidRuntime( 7359):        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/AndroidRuntime( 7359):        at uk.co.senab.actionbarpulltorefresh.library.PullToRefreshAttacher.<init>(PullToRefreshAttacher.java:110)
E/AndroidRuntime( 7359):        at uk.co.senab.actionbarpulltorefresh.library.PullToRefreshLayout.createPullToRefreshAttacher(PullToRefreshLayout.java:223)
E/AndroidRuntime( 7359):        at uk.co.senab.actionbarpulltorefresh.library.ActionBarPullToRefresh$SetupWizard.setup(ActionBarPullToRefresh.java:92)
E/AndroidRuntime( 7359):        at com.namelessdev.mpdroid.fragments.BrowseFragment.onViewCreated(BrowseFragment.java:342)
E/AndroidRuntime( 7359):        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:941)
E/AndroidRuntime( 7359):        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
E/AndroidRuntime( 7359):        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
E/AndroidRuntime( 7359):        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
E/AndroidRuntime( 7359):        at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:472)
E/AndroidRuntime( 7359):        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
E/AndroidRuntime( 7359):        at android.support.v4.view.ViewPager.populate(ViewPager.java:1068)
E/AndroidRuntime( 7359):        at android.support.v4.view.ViewPager.populate(ViewPager.java:914)
E/AndroidRuntime( 7359):        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1436)
E/AndroidRuntime( 7359):        at android.view.View.measure(View.java:16504)
E/AndroidRuntime( 7359):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime( 7359):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime( 7359):        at android.view.View.measure(View.java:16504)
E/AndroidRuntime( 7359):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime( 7359):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime( 7359):        at android.view.View.measure(View.java:16504)
E/AndroidRuntime( 7359):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime( 7359):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime( 7359):        at android.view.View.measure(View.java:16504)
E/AndroidRuntime( 7359):        at com.sothree.slidinguppanel.SlidingUpPanelLayout.onMeasure(SlidingUpPanelLayout.java:522)
E/AndroidRuntime( 7359):        at android.view.View.measure(View.java:16504)
E/AndroidRuntime( 7359):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime( 7359):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime( 7359):        at android.view.View.measure(View.java:16504)
E/AndroidRuntime( 7359):        at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:651)
E/AndroidRuntime( 7359):        at android.view.View.measure(View.java:16504)
E/AndroidRuntime( 7359):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime( 7359):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime( 7359):        at android.view.View.measure(View.java:16504)
E/AndroidRuntime( 7359):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime( 7359):        at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:327)
E/AndroidRuntime( 7359):        at android.view.View.measure(View.java:16504)
E/AndroidRuntime( 7359):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime( 7359):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime( 7359):        at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2552)
E/AndroidRuntime( 7359):        at android.view.View.measure(View.java:16504)
E/AndroidRuntime( 7359):        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1916)
E/AndroidRuntime( 7359):        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1113)
E/AndroidRuntime( 7359):        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1295)
E/AndroidRuntime( 7359):        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
E/AndroidRuntime( 7359):        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
E/AndroidRuntime( 7359):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
E/AndroidRuntime( 7359):        at android.view.Choreographer.doCallbacks(Choreographer.java:574)
E/AndroidRuntime( 7359):        at android.view.Choreographer.doFrame(Choreographer.java:544)
E/AndroidRuntime( 7359):        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreogra
W/ActivityManager( 2303):   Force finishing activity com.namelessdev.mpdroid/.MainMenuActivity
```

**Comment by IlyaEremin** [comment]
@hurzl thanks! Your answer helped me :)

**Comment by NehaDhanwani** [comment]
m facing same.. how to solve?

**Comment by abarisain** [comment]
maybe try cleaning your compilation cache ?
