### ISSUE TITLE
StreamsFragment: Crash on delete

### ISSUE THREAD

**Issue by avuton** [abarisain/dmix#632]
This was reported via Crashlytics bug 41 against 1.07b8.

```
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
       at java.util.ArrayList.remove(ArrayList.java:399)
       at com.namelessdev.mpdroid.fragments.StreamsFragment$DeleteDialogClickListener.onClick(StreamsFragment.java:77)
       at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:172)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5129)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by avuton** [comment]
Pretty sure I fixed this at some point. More fixes to come for this fragment!
