### ISSUE TITLE
NetworkOnMainThread exception when retrying

### ISSUE THREAD

**Issue by abarisain** [abarisain/dmix#722]
```
java.lang.RuntimeException: Unable to resume activity {com.namelessdev.mpdroid/com.namelessdev.mpdroid.MainMenuActivity}: android.os.NetworkOnMainThreadException
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2951)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2982)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
at android.app.ActivityThread.access$800(ActivityThread.java:144)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by: android.os.NetworkOnMainThreadException
at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
at java.net.InetAddress.getByName(InetAddress.java:305)
at com.anpmech.mpd.MPD.connect(MPD.java:644)
at com.namelessdev.mpdroid.MPDApplication.connect(MPDApplication.java:195)
at com.namelessdev.mpdroid.MPDApplication.checkConnectionNeeded(MPDApplication.java:176)
at com.namelessdev.mpdroid.MPDApplication.addConnectionLock(MPDApplication.java:125)
at com.namelessdev.mpdroid.ErrorHandler.<init>(ErrorHandler.java:84)
at com.namelessdev.mpdroid.MainMenuActivity.onResume(MainMenuActivity.java:209)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1241)
at android.app.Activity.performResume(Activity.java:6019)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2940)
... 11 more
```

**Comment by avuton** [comment]
Fixed.
