### ISSUE TITLE
Crash on Latest Develop Branch

### ISSUE THREAD

**Issue by caffinatedmonkey** [abarisain/dmix#766]
I am experiencing a crash when the app is starting on c1fdb4c422dd07ec9bb1cb4876b435ce72c128a7 in the develop branch. Here is the trace:

```
10-09 23:24:11.610    6542-6542/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.namelessdev.mpdroid, PID: 6542
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/anpmech/mpd/MPD;
            at com.namelessdev.mpdroid.MPDApplication.onCreate(MPDApplication.java:412)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4590)
            at android.app.ActivityThread.access$1600(ActivityThread.java:154)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5291)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.anpmech.mpd.MPD" on path: DexPathList[[zip file "/data/app/com.namelessdev.mpdroid-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at com.namelessdev.mpdroid.MPDApplication.onCreate(MPDApplication.java:412)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4590)
            at android.app.ActivityThread.access$1600(ActivityThread.java:154)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5291)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
    Suppressed: java.lang.ClassNotFoundException: com.anpmech.mpd.MPD
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 13 more
```

I tried clearing my data (#753), but that change anything.

**Comment by caffinatedmonkey** [comment]
Local issue. Oops. Cleaning then rebuilding fixed it.
