### ISSUE TITLE
Fix for not pausing on phone call

### ISSUE THREAD

**Issue by hurzl** [abarisain/dmix#794]
instead:

```
       java.lang.RuntimeException: Unable to start receiver com.namelessdev.mpdroid.PhoneStateReceiver: java.lang.ClassCastException: android.app.ReceiverRestrictedContext cannot be cast to com.namelessdev.mpdroid.MPDApplication
                                                                             at android.app.ActivityThread.handleReceiver(ActivityThread.java:2649)
                                                                             at android.app.ActivityThread.access$1800(ActivityThread.java:154)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                                                                          Caused by: java.lang.ClassCastException: android.app.ReceiverRestrictedContext cannot be cast to com.namelessdev.mpdroid.MPDApplication
                                                                             at com.namelessdev.mpdroid.PhoneStateReceiver$PauseForCall.run(PhoneStateReceiver.java:271)
                                                                             at com.namelessdev.mpdroid.PhoneStateReceiver.handleCall(PhoneStateReceiver.java:142)
                                                                             at com.namelessdev.mpdroid.PhoneStateReceiver.onReceive(PhoneStateReceiver.java:178)
                                                                             at android.app.ActivityThread.handleReceiver(ActivityThread.java:2642)
                                                                             at android.app.ActivityThread.access$1800(ActivityThread.java:154) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5294) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 

```

**Comment by fooness** [comment]
Will this be updated in the play store?

**Comment by abarisain** [comment]
The issue isn't fixed, and MPDroid is unlikely to get a release anytime soon

**Comment by hurzl** [comment]
my latest bet on it is
```
@@ -266,11 +266,11 @@ public class PhoneStateReceiver extends BroadcastReceiver {
             return mSettings.getBoolean(key, false);
         }
 
         @Override
         public void run() {
-            final MPDApplication app = (MPDApplication) mContext.getApplicationContext();
+            final MPDApplication app = MPDApplication.getInstance();
 
             try {
                 setMarker(PAUSING_MARKER);
                 app.addConnectionLock(this);
 ```

would this fix it for you?

**Comment by fooness** [comment]
I hope you’re talking to @abarisain — unfortunately I have no experience in java app programming.

**Comment by hurzl** [comment]
;-) anyone who wants to try ...

**Comment by abarisain** [comment]
Yeah that's probably the problem

**Comment by hurzl** [comment]
That nobody wants to try?

**Comment by abarisain** [comment]
I mean, it looks like an appropriate fix

**Comment by hurzl** [comment]
Ah ;)  yes I think it worked for me
(not using it because in flight mode it does not react to fritzbox phonecall signals over wifi :-( )
