### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by hurzl** [abarisain/dmix#800]
when deleting album from playlist

```
com.namelessdev.mpdroid E/AndroidRuntime: FATAL EXCEPTION: Thread-447
                                                                       Process: com.namelessdev.mpdroid, PID: 7979
                                                                       Theme: themes:{}
                                                                       java.util.ConcurrentModificationException
                                                                           at java.util.AbstractList$FullListIterator.previous(AbstractList.java:133)
                                                                           at com.anpmech.mpd.Tools.sequentialToRange(Tools.java:428)
                                                                           at com.anpmech.mpd.MPDPlaylist.removeByIndex(MPDPlaylist.java:446)
                                                                           at com.anpmech.mpd.MPDPlaylist.removeAlbumById(MPDPlaylist.java:375)
                                                                           at com.namelessdev.mpdroid.helpers.QueueControl$4.run(QueueControl.java:203)
                                                                           at java.lang.Thread.run(Thread.java:818)
```

**Comment by hurzl** [comment]
Only on Android 6, on Android 5 device no problem
